#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decili.Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parset")]
	public partial class AdvertisesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdsTags(AdsTags instance);
    partial void UpdateAdsTags(AdsTags instance);
    partial void DeleteAdsTags(AdsTags instance);
    partial void InsertAdvertises(Advertises instance);
    partial void UpdateAdvertises(Advertises instance);
    partial void DeleteAdvertises(Advertises instance);
    partial void InsertAdvertiseUpdateLogs(AdvertiseUpdateLogs instance);
    partial void UpdateAdvertiseUpdateLogs(AdvertiseUpdateLogs instance);
    partial void DeleteAdvertiseUpdateLogs(AdvertiseUpdateLogs instance);
    #endregion
		
		public AdvertisesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DeciliConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vAdvertiseKeywords> vAdvertiseKeywords
		{
			get
			{
				return this.GetTable<vAdvertiseKeywords>();
			}
		}
		
		public System.Data.Linq.Table<AdvertiseCats> AdvertiseCats
		{
			get
			{
				return this.GetTable<AdvertiseCats>();
			}
		}
		
		public System.Data.Linq.Table<vAdvertiseKeyworsFull> vAdvertiseKeyworsFulls
		{
			get
			{
				return this.GetTable<vAdvertiseKeyworsFull>();
			}
		}
		
		public System.Data.Linq.Table<vActiveAdvertises> vActiveAdvertises
		{
			get
			{
				return this.GetTable<vActiveAdvertises>();
			}
		}
		
		public System.Data.Linq.Table<vActiveFreeAds> vActiveFreeAds
		{
			get
			{
				return this.GetTable<vActiveFreeAds>();
			}
		}
		
		public System.Data.Linq.Table<AdsTags> AdsTags
		{
			get
			{
				return this.GetTable<AdsTags>();
			}
		}
		
		public System.Data.Linq.Table<Advertises> Advertises
		{
			get
			{
				return this.GetTable<Advertises>();
			}
		}
		
		public System.Data.Linq.Table<AdvertiseUpdateLogs> AdvertiseUpdateLogs
		{
			get
			{
				return this.GetTable<AdvertiseUpdateLogs>();
			}
		}
		
		public System.Data.Linq.Table<vAdvertises> vAdvertises
		{
			get
			{
				return this.GetTable<vAdvertises>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetRelatedAdvertises")]
		public ISingleResult<spGetRelatedAdvertisesResult> spGetRelatedAdvertises([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdvertiseCode", DbType="Int")] System.Nullable<int> advertiseCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), advertiseCode);
			return ((ISingleResult<spGetRelatedAdvertisesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetGeneralKeyByCatCode")]
		public ISingleResult<spGetGeneralKeyByCatCodeResult> spGetGeneralKeyByCatCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CatCode", DbType="Int")] System.Nullable<int> catCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), catCode);
			return ((ISingleResult<spGetGeneralKeyByCatCodeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetRelatedAdsKeywords")]
		public ISingleResult<spGetRelatedAdsKeywordsResult> spGetRelatedAdsKeywords([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeywordCode", DbType="Int")] System.Nullable<int> keywordCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywordCode);
			return ((ISingleResult<spGetRelatedAdsKeywordsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetAdverNews")]
		public ISingleResult<spGetAdverNewsResult> spGetAdverNews([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdvertiseCode", DbType="Int")] System.Nullable<int> advertiseCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), advertiseCode);
			return ((ISingleResult<spGetAdverNewsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetNewsAdvertises")]
		public ISingleResult<spGetNewsAdvertisesResult> spGetNewsAdvertises([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsCode", DbType="Int")] System.Nullable<int> newsCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), newsCode);
			return ((ISingleResult<spGetNewsAdvertisesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetAdKeywordsBySearchPhrase")]
		public ISingleResult<vAdvertiseKeyworsFull> spGetAdKeywordsBySearchPhrase([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WhereClause", DbType="NVarChar(1000)")] string whereClause)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), whereClause);
			return ((ISingleResult<vAdvertiseKeyworsFull>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAdvertiseKeywords")]
	public partial class vAdvertiseKeywords
	{
		
		private int _AdvertiseCode;
		
		private int _HCEntityTypeCode;
		
		private string _Keyword;
		
		private int _KeywordCode;
		
		public vAdvertiseKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiseCode", DbType="Int NOT NULL")]
		public int AdvertiseCode
		{
			get
			{
				return this._AdvertiseCode;
			}
			set
			{
				if ((this._AdvertiseCode != value))
				{
					this._AdvertiseCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this._HCEntityTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvertiseCats")]
	public partial class AdvertiseCats
	{
		
		private int _Code;
		
		private string _Title;
		
		private System.Nullable<int> _MasterCode;
		
		private System.Nullable<int> _ShowOrder;
		
		public AdvertiseCats()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					this._MasterCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowOrder", DbType="Int")]
		public System.Nullable<int> ShowOrder
		{
			get
			{
				return this._ShowOrder;
			}
			set
			{
				if ((this._ShowOrder != value))
				{
					this._ShowOrder = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAdvertiseKeyworsFull")]
	public partial class vAdvertiseKeyworsFull
	{
		
		private int _AdvertiseCode;
		
		private int _HCEntityTypeCode;
		
		private string _Keyword;
		
		private int _KeywordCode;
		
		private string _ID;
		
		private string _Title;
		
		private string _SmallPicFile;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private int _HCAdvertiseStatusCode;
		
		private int _Rate;
		
		private int _UserCode;
		
		private string _Tel;
		
		private string _Name;
		
		private int _CatCode;
		
		private string _Description;
		
		public vAdvertiseKeyworsFull()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiseCode", DbType="Int NOT NULL")]
		public int AdvertiseCode
		{
			get
			{
				return this._AdvertiseCode;
			}
			set
			{
				if ((this._AdvertiseCode != value))
				{
					this._AdvertiseCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this._HCEntityTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int NOT NULL")]
		public int HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this._HCAdvertiseStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int NOT NULL")]
		public int Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int NOT NULL")]
		public int CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vActiveAdvertises")]
	public partial class vActiveAdvertises
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private int _Rate;
		
		private int _HCAdvertiseStatusCode;
		
		private System.Nullable<int> _HCStateCode;
		
		private string _SmallPicFile;
		
		private int _UserCode;
		
		private string _Name;
		
		private string _Tel;
		
		private string _Description;
		
		private string _ShamsiCreateDate;
		
		private int _CatCode;
		
		private string _CatName;
		
		private System.Nullable<int> _MasterCatCode;
		
		private System.Nullable<int> _CityCode;
		
		private System.Nullable<int> _ProvinceCode;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		public vActiveAdvertises()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int NOT NULL")]
		public int Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int NOT NULL")]
		public int HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this._HCAdvertiseStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCStateCode", DbType="Int")]
		public System.Nullable<int> HCStateCode
		{
			get
			{
				return this._HCStateCode;
			}
			set
			{
				if ((this._HCStateCode != value))
				{
					this._HCStateCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShamsiCreateDate", DbType="VarChar(10)")]
		public string ShamsiCreateDate
		{
			get
			{
				return this._ShamsiCreateDate;
			}
			set
			{
				if ((this._ShamsiCreateDate != value))
				{
					this._ShamsiCreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int NOT NULL")]
		public int CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCatCode", DbType="Int")]
		public System.Nullable<int> MasterCatCode
		{
			get
			{
				return this._MasterCatCode;
			}
			set
			{
				if ((this._MasterCatCode != value))
				{
					this._MasterCatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int")]
		public System.Nullable<int> CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this._CityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceCode", DbType="Int")]
		public System.Nullable<int> ProvinceCode
		{
			get
			{
				return this._ProvinceCode;
			}
			set
			{
				if ((this._ProvinceCode != value))
				{
					this._ProvinceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vActiveFreeAds")]
	public partial class vActiveFreeAds
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private int _Rate;
		
		private int _HCAdvertiseStatusCode;
		
		private System.Nullable<int> _HCStateCode;
		
		private string _SmallPicFile;
		
		private int _UserCode;
		
		private string _Name;
		
		private string _Tel;
		
		private string _Description;
		
		private string _ShamsiCreateDate;
		
		private int _CatCode;
		
		private System.Nullable<int> _CityCode;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		public vActiveFreeAds()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int NOT NULL")]
		public int Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int NOT NULL")]
		public int HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this._HCAdvertiseStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCStateCode", DbType="Int")]
		public System.Nullable<int> HCStateCode
		{
			get
			{
				return this._HCStateCode;
			}
			set
			{
				if ((this._HCStateCode != value))
				{
					this._HCStateCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShamsiCreateDate", DbType="VarChar(10)")]
		public string ShamsiCreateDate
		{
			get
			{
				return this._ShamsiCreateDate;
			}
			set
			{
				if ((this._ShamsiCreateDate != value))
				{
					this._ShamsiCreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int NOT NULL")]
		public int CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int")]
		public System.Nullable<int> CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this._CityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdsTags")]
	public partial class AdsTags : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Keyword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnKeywordChanging(string value);
    partial void OnKeywordChanged();
    #endregion
		
		public AdsTags()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(200)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this.OnKeywordChanging(value);
					this.SendPropertyChanging();
					this._Keyword = value;
					this.SendPropertyChanged("Keyword");
					this.OnKeywordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Advertises")]
	public partial class Advertises : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private string _Description;
		
		private string _Name;
		
		private string _Tel;
		
		private int _CatCode;
		
		private System.Nullable<int> _HCDurationCode;
		
		private string _Price;
		
		private System.Nullable<int> _HCStateCode;
		
		private string _Address;
		
		private string _FishNo;
		
		private System.Nullable<int> _Amount;
		
		private System.Nullable<System.DateTime> _PayDate;
		
		private int _Rate;
		
		private bool _ShowContactAdvetiserWin;
		
		private string _Link;
		
		private System.Nullable<bool> _LinkActivated;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private int _HCAdvertiseStatusCode;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private string _SmallPicFile;
		
		private string _LargePicFile;
		
		private int _UserCode;
		
		private int _ViewCount;
		
		private System.Nullable<int> _CityCode;
		
		private string _ADUrl;
		
		private string _LatX;
		
		private string _LatY;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<System.DateTime> _DeciExpDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnCatCodeChanging(int value);
    partial void OnCatCodeChanged();
    partial void OnHCDurationCodeChanging(System.Nullable<int> value);
    partial void OnHCDurationCodeChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnHCStateCodeChanging(System.Nullable<int> value);
    partial void OnHCStateCodeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnFishNoChanging(string value);
    partial void OnFishNoChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    partial void OnPayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPayDateChanged();
    partial void OnRateChanging(int value);
    partial void OnRateChanged();
    partial void OnShowContactAdvetiserWinChanging(bool value);
    partial void OnShowContactAdvetiserWinChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnLinkActivatedChanging(System.Nullable<bool> value);
    partial void OnLinkActivatedChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnHCAdvertiseStatusCodeChanging(int value);
    partial void OnHCAdvertiseStatusCodeChanged();
    partial void OnExpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpDateChanged();
    partial void OnSmallPicFileChanging(string value);
    partial void OnSmallPicFileChanged();
    partial void OnLargePicFileChanging(string value);
    partial void OnLargePicFileChanged();
    partial void OnUserCodeChanging(int value);
    partial void OnUserCodeChanged();
    partial void OnViewCountChanging(int value);
    partial void OnViewCountChanged();
    partial void OnCityCodeChanging(System.Nullable<int> value);
    partial void OnCityCodeChanged();
    partial void OnADUrlChanging(string value);
    partial void OnADUrlChanged();
    partial void OnLatXChanging(string value);
    partial void OnLatXChanged();
    partial void OnLatYChanging(string value);
    partial void OnLatYChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeciExpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeciExpDateChanged();
    #endregion
		
		public Advertises()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int NOT NULL")]
		public int CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this.OnCatCodeChanging(value);
					this.SendPropertyChanging();
					this._CatCode = value;
					this.SendPropertyChanged("CatCode");
					this.OnCatCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCDurationCode", DbType="Int")]
		public System.Nullable<int> HCDurationCode
		{
			get
			{
				return this._HCDurationCode;
			}
			set
			{
				if ((this._HCDurationCode != value))
				{
					this.OnHCDurationCodeChanging(value);
					this.SendPropertyChanging();
					this._HCDurationCode = value;
					this.SendPropertyChanged("HCDurationCode");
					this.OnHCDurationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="NVarChar(200)")]
		public string Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCStateCode", DbType="Int")]
		public System.Nullable<int> HCStateCode
		{
			get
			{
				return this._HCStateCode;
			}
			set
			{
				if ((this._HCStateCode != value))
				{
					this.OnHCStateCodeChanging(value);
					this.SendPropertyChanging();
					this._HCStateCode = value;
					this.SendPropertyChanged("HCStateCode");
					this.OnHCStateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(200)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FishNo", DbType="NVarChar(200)")]
		public string FishNo
		{
			get
			{
				return this._FishNo;
			}
			set
			{
				if ((this._FishNo != value))
				{
					this.OnFishNoChanging(value);
					this.SendPropertyChanging();
					this._FishNo = value;
					this.SendPropertyChanged("FishNo");
					this.OnFishNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PayDate
		{
			get
			{
				return this._PayDate;
			}
			set
			{
				if ((this._PayDate != value))
				{
					this.OnPayDateChanging(value);
					this.SendPropertyChanging();
					this._PayDate = value;
					this.SendPropertyChanged("PayDate");
					this.OnPayDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int NOT NULL")]
		public int Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowContactAdvetiserWin", DbType="Bit NOT NULL")]
		public bool ShowContactAdvetiserWin
		{
			get
			{
				return this._ShowContactAdvetiserWin;
			}
			set
			{
				if ((this._ShowContactAdvetiserWin != value))
				{
					this.OnShowContactAdvetiserWinChanging(value);
					this.SendPropertyChanging();
					this._ShowContactAdvetiserWin = value;
					this.SendPropertyChanged("ShowContactAdvetiserWin");
					this.OnShowContactAdvetiserWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(200)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkActivated", DbType="Bit")]
		public System.Nullable<bool> LinkActivated
		{
			get
			{
				return this._LinkActivated;
			}
			set
			{
				if ((this._LinkActivated != value))
				{
					this.OnLinkActivatedChanging(value);
					this.SendPropertyChanging();
					this._LinkActivated = value;
					this.SendPropertyChanged("LinkActivated");
					this.OnLinkActivatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int NOT NULL")]
		public int HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this.OnHCAdvertiseStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCAdvertiseStatusCode = value;
					this.SendPropertyChanged("HCAdvertiseStatusCode");
					this.OnHCAdvertiseStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this.OnExpDateChanging(value);
					this.SendPropertyChanging();
					this._ExpDate = value;
					this.SendPropertyChanged("ExpDate");
					this.OnExpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this.OnSmallPicFileChanging(value);
					this.SendPropertyChanging();
					this._SmallPicFile = value;
					this.SendPropertyChanged("SmallPicFile");
					this.OnSmallPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargePicFile", DbType="NVarChar(200)")]
		public string LargePicFile
		{
			get
			{
				return this._LargePicFile;
			}
			set
			{
				if ((this._LargePicFile != value))
				{
					this.OnLargePicFileChanging(value);
					this.SendPropertyChanging();
					this._LargePicFile = value;
					this.SendPropertyChanged("LargePicFile");
					this.OnLargePicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewCount", DbType="Int NOT NULL")]
		public int ViewCount
		{
			get
			{
				return this._ViewCount;
			}
			set
			{
				if ((this._ViewCount != value))
				{
					this.OnViewCountChanging(value);
					this.SendPropertyChanging();
					this._ViewCount = value;
					this.SendPropertyChanged("ViewCount");
					this.OnViewCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int")]
		public System.Nullable<int> CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this.OnCityCodeChanging(value);
					this.SendPropertyChanging();
					this._CityCode = value;
					this.SendPropertyChanged("CityCode");
					this.OnCityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADUrl", DbType="NVarChar(450)")]
		public string ADUrl
		{
			get
			{
				return this._ADUrl;
			}
			set
			{
				if ((this._ADUrl != value))
				{
					this.OnADUrlChanging(value);
					this.SendPropertyChanging();
					this._ADUrl = value;
					this.SendPropertyChanged("ADUrl");
					this.OnADUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatX", DbType="VarChar(50)")]
		public string LatX
		{
			get
			{
				return this._LatX;
			}
			set
			{
				if ((this._LatX != value))
				{
					this.OnLatXChanging(value);
					this.SendPropertyChanging();
					this._LatX = value;
					this.SendPropertyChanged("LatX");
					this.OnLatXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatY", DbType="VarChar(50)")]
		public string LatY
		{
			get
			{
				return this._LatY;
			}
			set
			{
				if ((this._LatY != value))
				{
					this.OnLatYChanging(value);
					this.SendPropertyChanging();
					this._LatY = value;
					this.SendPropertyChanged("LatY");
					this.OnLatYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeciExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeciExpDate
		{
			get
			{
				return this._DeciExpDate;
			}
			set
			{
				if ((this._DeciExpDate != value))
				{
					this.OnDeciExpDateChanging(value);
					this.SendPropertyChanging();
					this._DeciExpDate = value;
					this.SendPropertyChanged("DeciExpDate");
					this.OnDeciExpDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdvertiseUpdateLogs")]
	public partial class AdvertiseUpdateLogs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _AdvertiseCode;
		
		private System.DateTime _UpdateDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnAdvertiseCodeChanging(int value);
    partial void OnAdvertiseCodeChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    #endregion
		
		public AdvertiseUpdateLogs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiseCode", DbType="Int NOT NULL")]
		public int AdvertiseCode
		{
			get
			{
				return this._AdvertiseCode;
			}
			set
			{
				if ((this._AdvertiseCode != value))
				{
					this.OnAdvertiseCodeChanging(value);
					this.SendPropertyChanging();
					this._AdvertiseCode = value;
					this.SendPropertyChanged("AdvertiseCode");
					this.OnAdvertiseCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAdvertises")]
	public partial class vAdvertises
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _Status;
		
		private string _ID;
		
		private string _Name;
		
		private string _CDate;
		
		private string _UDate;
		
		private string _Tel;
		
		private string _Duration;
		
		private string _CatName;
		
		private string _Price;
		
		private string _FishNo;
		
		private string _User;
		
		private string _Description;
		
		private string _Address;
		
		private int _Rate;
		
		private string _SmallPicFile;
		
		private string _LargePicFile;
		
		private string _EDate;
		
		private string _Link;
		
		private string _StateName;
		
		private string _Email;
		
		private int _UserCode;
		
		private int _HCAdvertiseStatusCode;
		
		private bool _ShowContactAdvetiserWin;
		
		private int _ViewCount;
		
		private string _RateName;
		
		private int _CatCode;
		
		private string _LatX;
		
		private string _LatY;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private System.Nullable<int> _CityCode;
		
		private string _CityName;
		
		private string _ProvinceName;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<bool> _LinkActivated;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		public vAdvertises()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(500)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDate", DbType="VarChar(10)")]
		public string CDate
		{
			get
			{
				return this._CDate;
			}
			set
			{
				if ((this._CDate != value))
				{
					this._CDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UDate", DbType="VarChar(10)")]
		public string UDate
		{
			get
			{
				return this._UDate;
			}
			set
			{
				if ((this._UDate != value))
				{
					this._UDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="NVarChar(500)")]
		public string Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="NVarChar(200)")]
		public string Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FishNo", DbType="NVarChar(200)")]
		public string FishNo
		{
			get
			{
				return this._FishNo;
			}
			set
			{
				if ((this._FishNo != value))
				{
					this._FishNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(101)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(200)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int NOT NULL")]
		public int Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargePicFile", DbType="NVarChar(200)")]
		public string LargePicFile
		{
			get
			{
				return this._LargePicFile;
			}
			set
			{
				if ((this._LargePicFile != value))
				{
					this._LargePicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDate", DbType="VarChar(10)")]
		public string EDate
		{
			get
			{
				return this._EDate;
			}
			set
			{
				if ((this._EDate != value))
				{
					this._EDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(200)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateName", DbType="NVarChar(500)")]
		public string StateName
		{
			get
			{
				return this._StateName;
			}
			set
			{
				if ((this._StateName != value))
				{
					this._StateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int NOT NULL")]
		public int HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this._HCAdvertiseStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowContactAdvetiserWin", DbType="Bit NOT NULL")]
		public bool ShowContactAdvetiserWin
		{
			get
			{
				return this._ShowContactAdvetiserWin;
			}
			set
			{
				if ((this._ShowContactAdvetiserWin != value))
				{
					this._ShowContactAdvetiserWin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewCount", DbType="Int NOT NULL")]
		public int ViewCount
		{
			get
			{
				return this._ViewCount;
			}
			set
			{
				if ((this._ViewCount != value))
				{
					this._ViewCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RateName", DbType="NVarChar(500)")]
		public string RateName
		{
			get
			{
				return this._RateName;
			}
			set
			{
				if ((this._RateName != value))
				{
					this._RateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int NOT NULL")]
		public int CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatX", DbType="VarChar(50)")]
		public string LatX
		{
			get
			{
				return this._LatX;
			}
			set
			{
				if ((this._LatX != value))
				{
					this._LatX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatY", DbType="VarChar(50)")]
		public string LatY
		{
			get
			{
				return this._LatY;
			}
			set
			{
				if ((this._LatY != value))
				{
					this._LatY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int")]
		public System.Nullable<int> CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this._CityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityName", DbType="NVarChar(100)")]
		public string CityName
		{
			get
			{
				return this._CityName;
			}
			set
			{
				if ((this._CityName != value))
				{
					this._CityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceName", DbType="NVarChar(100)")]
		public string ProvinceName
		{
			get
			{
				return this._ProvinceName;
			}
			set
			{
				if ((this._ProvinceName != value))
				{
					this._ProvinceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkActivated", DbType="Bit")]
		public System.Nullable<bool> LinkActivated
		{
			get
			{
				return this._LinkActivated;
			}
			set
			{
				if ((this._LinkActivated != value))
				{
					this._LinkActivated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
	}
	
	public partial class spGetRelatedAdvertisesResult
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private System.Nullable<int> _Rate;
		
		private System.Nullable<int> _HCAdvertiseStatusCode;
		
		private System.Nullable<int> _HCStateCode;
		
		private string _SmallPicFile;
		
		private System.Nullable<int> _UserCode;
		
		private string _Name;
		
		private string _Tel;
		
		public spGetRelatedAdvertisesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int")]
		public System.Nullable<int> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int")]
		public System.Nullable<int> HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this._HCAdvertiseStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCStateCode", DbType="Int")]
		public System.Nullable<int> HCStateCode
		{
			get
			{
				return this._HCStateCode;
			}
			set
			{
				if ((this._HCStateCode != value))
				{
					this._HCStateCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
	}
	
	public partial class spGetGeneralKeyByCatCodeResult
	{
		
		private int _KeywordCode;
		
		private string _Keyword;
		
		public spGetGeneralKeyByCatCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
	}
	
	public partial class spGetRelatedAdsKeywordsResult
	{
		
		private System.Nullable<int> _Column1;
		
		private string _Keyword;
		
		private int _KeywordCode;
		
		public spGetRelatedAdsKeywordsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
	}
	
	public partial class spGetAdverNewsResult
	{
		
		private System.Nullable<int> _ResouseSiteCode;
		
		private int _Code;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _NewsDate;
		
		public spGetAdverNewsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResouseSiteCode", DbType="Int")]
		public System.Nullable<int> ResouseSiteCode
		{
			get
			{
				return this._ResouseSiteCode;
			}
			set
			{
				if ((this._ResouseSiteCode != value))
				{
					this._ResouseSiteCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
	}
	
	public partial class spGetNewsAdvertisesResult
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private int _Rate;
		
		private int _HCAdvertiseStatusCode;
		
		private System.Nullable<int> _HCStateCode;
		
		private string _SmallPicFile;
		
		private int _UserCode;
		
		private string _Name;
		
		private string _Tel;
		
		private string _Description;
		
		private string _ShamsiCreateDate;
		
		private int _CatCode;
		
		private string _CatName;
		
		private System.Nullable<int> _MasterCatCode;
		
		public spGetNewsAdvertisesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Int NOT NULL")]
		public int Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAdvertiseStatusCode", DbType="Int NOT NULL")]
		public int HCAdvertiseStatusCode
		{
			get
			{
				return this._HCAdvertiseStatusCode;
			}
			set
			{
				if ((this._HCAdvertiseStatusCode != value))
				{
					this._HCAdvertiseStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCStateCode", DbType="Int")]
		public System.Nullable<int> HCStateCode
		{
			get
			{
				return this._HCStateCode;
			}
			set
			{
				if ((this._HCStateCode != value))
				{
					this._HCStateCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShamsiCreateDate", DbType="VarChar(10)")]
		public string ShamsiCreateDate
		{
			get
			{
				return this._ShamsiCreateDate;
			}
			set
			{
				if ((this._ShamsiCreateDate != value))
				{
					this._ShamsiCreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int NOT NULL")]
		public int CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCatCode", DbType="Int")]
		public System.Nullable<int> MasterCatCode
		{
			get
			{
				return this._MasterCatCode;
			}
			set
			{
				if ((this._MasterCatCode != value))
				{
					this._MasterCatCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
