<?xml version="1.0" encoding="utf-8"?><Database Name="Decili" Class="EmailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Parset;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DeciliConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Emails" Member="Emails">
    <Type Name="Emails">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HCSectionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmailList" Member="EmailLists">
    <Type Name="EmailList">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.spMarkSent" Method="spMarkSent">
    <Parameter Name="CodeList" Parameter="codeList" Type="System.String" DbType="VarChar(2000)" />
    <Return Type="System.Int32" />
  </Function>
</Database>