<?xml version="1.0" encoding="utf-8"?><Database Name="Parset" Class="NewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Parset;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DeciliConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vRandNews" Member="vRandNews">
    <Type Name="vRandNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="News">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShortDesc" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="PicDesc" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Resource" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCNewsCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vNews" Member="vNews">
    <Type Name="vNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsTitle" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ShortDesc" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>