#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decili.Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parset")]
	public partial class ParsetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public ParsetDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DeciliConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ParsetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParsetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParsetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParsetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _ID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Username;
		
		private System.Nullable<int> _HCMembershipTypeCode;
		
		private System.Nullable<System.DateTime> _MembershipExpDate;
		
		private string _Email;
		
		private string _Password;
		
		private string _Address;
		
		private string _City;
		
		private System.Nullable<int> _StateCode;
		
		private System.Nullable<int> _HCCountryCode;
		
		private System.Nullable<int> _HCHintQuestionCode;
		
		private string _HintAnswer;
		
		private string _BirthDay;
		
		private System.Nullable<bool> _AutoLogin;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _HCGenderCode;
		
		private string _Comment;
		
		private System.Nullable<bool> _ShowBirthDate;
		
		private System.Nullable<bool> _AdminPanelUser;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private System.Nullable<int> _CountryCode;
		
		private string _Location;
		
		private string _PicFile;
		
		private string _SmallPicFile;
		
		private string _FavBooks;
		
		private string _FavMovies;
		
		private string _ICQNumber;
		
		private System.Nullable<int> _HCRelationTypeCode;
		
		private string _DoForFun;
		
		private System.Nullable<System.DateTime> _UpdateTime;
		
		private System.Nullable<bool> _IInviteMeToJoinGroup;
		
		private System.Nullable<bool> _ISendMessage;
		
		private System.Nullable<bool> _IAddMeAsFriend;
		
		private System.Nullable<bool> _IConnectMeAsFan;
		
		private System.Nullable<bool> _IConfirmFriendshipReq;
		
		private System.Nullable<bool> _IPostMeGlobalMessage;
		
		private System.Nullable<bool> _IPostMePrivateMessage;
		
		private System.Nullable<bool> _ISuggestsFriends;
		
		private System.Nullable<bool> _IAcceptFriendISuggested;
		
		private System.Nullable<bool> _ITagsMeOnPhoto;
		
		private System.Nullable<bool> _ICommentOnMyPhoto;
		
		private System.Nullable<bool> _IRequestToJoinMyGroup;
		
		private System.Nullable<bool> _IInviteMeAnEvent;
		
		private System.Nullable<bool> _IChangeMyEventDate;
		
		private System.Nullable<bool> _ICommentOnMyNote;
		
		private System.Nullable<bool> _ICommentMyLink;
		
		private System.Nullable<bool> _ICommentAfterMeInLink;
		
		private System.Nullable<bool> _ICommentAfterMeOnGeneralMessage;
		
		private System.Nullable<bool> _RemindUpload;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _AIMNumber;
		
		private string _SkypeName;
		
		private string _JabberNumber;
		
		private string _MobileNumber;
		
		private string _Tel;
		
		private System.Nullable<int> _HCSeekGenderCode;
		
		private System.Nullable<int> _HCCamStatusCode;
		
		private System.Nullable<int> _HCUserTypeCode;
		
		private System.Nullable<int> _HCTallCode;
		
		private System.Nullable<int> _HCWeightCode;
		
		private System.Nullable<int> _HCHairColorCode;
		
		private System.Nullable<int> _HCEyeColorCode;
		
		private System.Nullable<int> _HCBodyTypeCode;
		
		private System.Nullable<int> _HCRaceCode;
		
		private System.Nullable<int> _HCMarritalStatusCode;
		
		private System.Nullable<int> _HCKidNoCode;
		
		private System.Nullable<int> _HCWantKidCode;
		
		private System.Nullable<int> _HCProfessionCode;
		
		private System.Nullable<int> _HCIncomeCode;
		
		private System.Nullable<int> _HCLang1Code;
		
		private System.Nullable<int> _HCLang2Code;
		
		private System.Nullable<int> _HCLang3Code;
		
		private System.Nullable<int> _HCLang4Code;
		
		private System.Nullable<int> _HCEducationCode;
		
		private System.Nullable<int> _HCPoliticalViewCode;
		
		private System.Nullable<int> _HCReligionCode;
		
		private System.Nullable<int> _HCSmokeCode;
		
		private System.Nullable<int> _HCAlcoholCode;
		
		private System.Nullable<int> _HCHumorCode;
		
		private string _Favorites;
		
		private string _HobbyComment;
		
		private string _EduComment;
		
		private string _RaceInfo;
		
		private string _EmailPassword;
		
		private string _DockState;
		
		private System.Nullable<int> _HCPicStatusCode;
		
		private System.Nullable<System.DateTime> _LastLoginTime;
		
		private System.Nullable<System.DateTime> _RegDate;
		
		private System.Nullable<bool> _AdsEmailSent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnHCMembershipTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCMembershipTypeCodeChanged();
    partial void OnMembershipExpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMembershipExpDateChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateCodeChanging(System.Nullable<int> value);
    partial void OnStateCodeChanged();
    partial void OnHCCountryCodeChanging(System.Nullable<int> value);
    partial void OnHCCountryCodeChanged();
    partial void OnHCHintQuestionCodeChanging(System.Nullable<int> value);
    partial void OnHCHintQuestionCodeChanged();
    partial void OnHintAnswerChanging(string value);
    partial void OnHintAnswerChanged();
    partial void OnBirthDayChanging(string value);
    partial void OnBirthDayChanged();
    partial void OnAutoLoginChanging(System.Nullable<bool> value);
    partial void OnAutoLoginChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnHCGenderCodeChanging(System.Nullable<int> value);
    partial void OnHCGenderCodeChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnShowBirthDateChanging(System.Nullable<bool> value);
    partial void OnShowBirthDateChanged();
    partial void OnAdminPanelUserChanging(System.Nullable<bool> value);
    partial void OnAdminPanelUserChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnCountryCodeChanging(System.Nullable<int> value);
    partial void OnCountryCodeChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnPicFileChanging(string value);
    partial void OnPicFileChanged();
    partial void OnSmallPicFileChanging(string value);
    partial void OnSmallPicFileChanged();
    partial void OnFavBooksChanging(string value);
    partial void OnFavBooksChanged();
    partial void OnFavMoviesChanging(string value);
    partial void OnFavMoviesChanged();
    partial void OnICQNumberChanging(string value);
    partial void OnICQNumberChanged();
    partial void OnHCRelationTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCRelationTypeCodeChanged();
    partial void OnDoForFunChanging(string value);
    partial void OnDoForFunChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    partial void OnIInviteMeToJoinGroupChanging(System.Nullable<bool> value);
    partial void OnIInviteMeToJoinGroupChanged();
    partial void OnISendMessageChanging(System.Nullable<bool> value);
    partial void OnISendMessageChanged();
    partial void OnIAddMeAsFriendChanging(System.Nullable<bool> value);
    partial void OnIAddMeAsFriendChanged();
    partial void OnIConnectMeAsFanChanging(System.Nullable<bool> value);
    partial void OnIConnectMeAsFanChanged();
    partial void OnIConfirmFriendshipReqChanging(System.Nullable<bool> value);
    partial void OnIConfirmFriendshipReqChanged();
    partial void OnIPostMeGlobalMessageChanging(System.Nullable<bool> value);
    partial void OnIPostMeGlobalMessageChanged();
    partial void OnIPostMePrivateMessageChanging(System.Nullable<bool> value);
    partial void OnIPostMePrivateMessageChanged();
    partial void OnISuggestsFriendsChanging(System.Nullable<bool> value);
    partial void OnISuggestsFriendsChanged();
    partial void OnIAcceptFriendISuggestedChanging(System.Nullable<bool> value);
    partial void OnIAcceptFriendISuggestedChanged();
    partial void OnITagsMeOnPhotoChanging(System.Nullable<bool> value);
    partial void OnITagsMeOnPhotoChanged();
    partial void OnICommentOnMyPhotoChanging(System.Nullable<bool> value);
    partial void OnICommentOnMyPhotoChanged();
    partial void OnIRequestToJoinMyGroupChanging(System.Nullable<bool> value);
    partial void OnIRequestToJoinMyGroupChanged();
    partial void OnIInviteMeAnEventChanging(System.Nullable<bool> value);
    partial void OnIInviteMeAnEventChanged();
    partial void OnIChangeMyEventDateChanging(System.Nullable<bool> value);
    partial void OnIChangeMyEventDateChanged();
    partial void OnICommentOnMyNoteChanging(System.Nullable<bool> value);
    partial void OnICommentOnMyNoteChanged();
    partial void OnICommentMyLinkChanging(System.Nullable<bool> value);
    partial void OnICommentMyLinkChanged();
    partial void OnICommentAfterMeInLinkChanging(System.Nullable<bool> value);
    partial void OnICommentAfterMeInLinkChanged();
    partial void OnICommentAfterMeOnGeneralMessageChanging(System.Nullable<bool> value);
    partial void OnICommentAfterMeOnGeneralMessageChanged();
    partial void OnRemindUploadChanging(System.Nullable<bool> value);
    partial void OnRemindUploadChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnAIMNumberChanging(string value);
    partial void OnAIMNumberChanged();
    partial void OnSkypeNameChanging(string value);
    partial void OnSkypeNameChanged();
    partial void OnJabberNumberChanging(string value);
    partial void OnJabberNumberChanged();
    partial void OnMobileNumberChanging(string value);
    partial void OnMobileNumberChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnHCSeekGenderCodeChanging(System.Nullable<int> value);
    partial void OnHCSeekGenderCodeChanged();
    partial void OnHCCamStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCCamStatusCodeChanged();
    partial void OnHCUserTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCUserTypeCodeChanged();
    partial void OnHCTallCodeChanging(System.Nullable<int> value);
    partial void OnHCTallCodeChanged();
    partial void OnHCWeightCodeChanging(System.Nullable<int> value);
    partial void OnHCWeightCodeChanged();
    partial void OnHCHairColorCodeChanging(System.Nullable<int> value);
    partial void OnHCHairColorCodeChanged();
    partial void OnHCEyeColorCodeChanging(System.Nullable<int> value);
    partial void OnHCEyeColorCodeChanged();
    partial void OnHCBodyTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCBodyTypeCodeChanged();
    partial void OnHCRaceCodeChanging(System.Nullable<int> value);
    partial void OnHCRaceCodeChanged();
    partial void OnHCMarritalStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCMarritalStatusCodeChanged();
    partial void OnHCKidNoCodeChanging(System.Nullable<int> value);
    partial void OnHCKidNoCodeChanged();
    partial void OnHCWantKidCodeChanging(System.Nullable<int> value);
    partial void OnHCWantKidCodeChanged();
    partial void OnHCProfessionCodeChanging(System.Nullable<int> value);
    partial void OnHCProfessionCodeChanged();
    partial void OnHCIncomeCodeChanging(System.Nullable<int> value);
    partial void OnHCIncomeCodeChanged();
    partial void OnHCLang1CodeChanging(System.Nullable<int> value);
    partial void OnHCLang1CodeChanged();
    partial void OnHCLang2CodeChanging(System.Nullable<int> value);
    partial void OnHCLang2CodeChanged();
    partial void OnHCLang3CodeChanging(System.Nullable<int> value);
    partial void OnHCLang3CodeChanged();
    partial void OnHCLang4CodeChanging(System.Nullable<int> value);
    partial void OnHCLang4CodeChanged();
    partial void OnHCEducationCodeChanging(System.Nullable<int> value);
    partial void OnHCEducationCodeChanged();
    partial void OnHCPoliticalViewCodeChanging(System.Nullable<int> value);
    partial void OnHCPoliticalViewCodeChanged();
    partial void OnHCReligionCodeChanging(System.Nullable<int> value);
    partial void OnHCReligionCodeChanged();
    partial void OnHCSmokeCodeChanging(System.Nullable<int> value);
    partial void OnHCSmokeCodeChanged();
    partial void OnHCAlcoholCodeChanging(System.Nullable<int> value);
    partial void OnHCAlcoholCodeChanged();
    partial void OnHCHumorCodeChanging(System.Nullable<int> value);
    partial void OnHCHumorCodeChanged();
    partial void OnFavoritesChanging(string value);
    partial void OnFavoritesChanged();
    partial void OnHobbyCommentChanging(string value);
    partial void OnHobbyCommentChanged();
    partial void OnEduCommentChanging(string value);
    partial void OnEduCommentChanged();
    partial void OnRaceInfoChanging(string value);
    partial void OnRaceInfoChanged();
    partial void OnEmailPasswordChanging(string value);
    partial void OnEmailPasswordChanged();
    partial void OnDockStateChanging(string value);
    partial void OnDockStateChanged();
    partial void OnHCPicStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCPicStatusCodeChanged();
    partial void OnLastLoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginTimeChanged();
    partial void OnRegDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegDateChanged();
    partial void OnAdsEmailSentChanging(System.Nullable<bool> value);
    partial void OnAdsEmailSentChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCMembershipTypeCode", DbType="Int")]
		public System.Nullable<int> HCMembershipTypeCode
		{
			get
			{
				return this._HCMembershipTypeCode;
			}
			set
			{
				if ((this._HCMembershipTypeCode != value))
				{
					this.OnHCMembershipTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCMembershipTypeCode = value;
					this.SendPropertyChanged("HCMembershipTypeCode");
					this.OnHCMembershipTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> MembershipExpDate
		{
			get
			{
				return this._MembershipExpDate;
			}
			set
			{
				if ((this._MembershipExpDate != value))
				{
					this.OnMembershipExpDateChanging(value);
					this.SendPropertyChanging();
					this._MembershipExpDate = value;
					this.SendPropertyChanged("MembershipExpDate");
					this.OnMembershipExpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateCode", DbType="Int")]
		public System.Nullable<int> StateCode
		{
			get
			{
				return this._StateCode;
			}
			set
			{
				if ((this._StateCode != value))
				{
					this.OnStateCodeChanging(value);
					this.SendPropertyChanging();
					this._StateCode = value;
					this.SendPropertyChanged("StateCode");
					this.OnStateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCCountryCode", DbType="Int")]
		public System.Nullable<int> HCCountryCode
		{
			get
			{
				return this._HCCountryCode;
			}
			set
			{
				if ((this._HCCountryCode != value))
				{
					this.OnHCCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._HCCountryCode = value;
					this.SendPropertyChanged("HCCountryCode");
					this.OnHCCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCHintQuestionCode", DbType="Int")]
		public System.Nullable<int> HCHintQuestionCode
		{
			get
			{
				return this._HCHintQuestionCode;
			}
			set
			{
				if ((this._HCHintQuestionCode != value))
				{
					this.OnHCHintQuestionCodeChanging(value);
					this.SendPropertyChanging();
					this._HCHintQuestionCode = value;
					this.SendPropertyChanged("HCHintQuestionCode");
					this.OnHCHintQuestionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HintAnswer", DbType="NVarChar(500)")]
		public string HintAnswer
		{
			get
			{
				return this._HintAnswer;
			}
			set
			{
				if ((this._HintAnswer != value))
				{
					this.OnHintAnswerChanging(value);
					this.SendPropertyChanging();
					this._HintAnswer = value;
					this.SendPropertyChanged("HintAnswer");
					this.OnHintAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDay", DbType="NVarChar(50)")]
		public string BirthDay
		{
			get
			{
				return this._BirthDay;
			}
			set
			{
				if ((this._BirthDay != value))
				{
					this.OnBirthDayChanging(value);
					this.SendPropertyChanging();
					this._BirthDay = value;
					this.SendPropertyChanged("BirthDay");
					this.OnBirthDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoLogin", DbType="Bit")]
		public System.Nullable<bool> AutoLogin
		{
			get
			{
				return this._AutoLogin;
			}
			set
			{
				if ((this._AutoLogin != value))
				{
					this.OnAutoLoginChanging(value);
					this.SendPropertyChanging();
					this._AutoLogin = value;
					this.SendPropertyChanged("AutoLogin");
					this.OnAutoLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCGenderCode", DbType="Int")]
		public System.Nullable<int> HCGenderCode
		{
			get
			{
				return this._HCGenderCode;
			}
			set
			{
				if ((this._HCGenderCode != value))
				{
					this.OnHCGenderCodeChanging(value);
					this.SendPropertyChanging();
					this._HCGenderCode = value;
					this.SendPropertyChanged("HCGenderCode");
					this.OnHCGenderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowBirthDate", DbType="Bit")]
		public System.Nullable<bool> ShowBirthDate
		{
			get
			{
				return this._ShowBirthDate;
			}
			set
			{
				if ((this._ShowBirthDate != value))
				{
					this.OnShowBirthDateChanging(value);
					this.SendPropertyChanging();
					this._ShowBirthDate = value;
					this.SendPropertyChanged("ShowBirthDate");
					this.OnShowBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPanelUser", DbType="Bit")]
		public System.Nullable<bool> AdminPanelUser
		{
			get
			{
				return this._AdminPanelUser;
			}
			set
			{
				if ((this._AdminPanelUser != value))
				{
					this.OnAdminPanelUserChanging(value);
					this.SendPropertyChanging();
					this._AdminPanelUser = value;
					this.SendPropertyChanged("AdminPanelUser");
					this.OnAdminPanelUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="Int")]
		public System.Nullable<int> CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(500)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile", DbType="NVarChar(200)")]
		public string PicFile
		{
			get
			{
				return this._PicFile;
			}
			set
			{
				if ((this._PicFile != value))
				{
					this.OnPicFileChanging(value);
					this.SendPropertyChanging();
					this._PicFile = value;
					this.SendPropertyChanged("PicFile");
					this.OnPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this.OnSmallPicFileChanging(value);
					this.SendPropertyChanging();
					this._SmallPicFile = value;
					this.SendPropertyChanged("SmallPicFile");
					this.OnSmallPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FavBooks", DbType="NVarChar(500)")]
		public string FavBooks
		{
			get
			{
				return this._FavBooks;
			}
			set
			{
				if ((this._FavBooks != value))
				{
					this.OnFavBooksChanging(value);
					this.SendPropertyChanging();
					this._FavBooks = value;
					this.SendPropertyChanged("FavBooks");
					this.OnFavBooksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FavMovies", DbType="NVarChar(500)")]
		public string FavMovies
		{
			get
			{
				return this._FavMovies;
			}
			set
			{
				if ((this._FavMovies != value))
				{
					this.OnFavMoviesChanging(value);
					this.SendPropertyChanging();
					this._FavMovies = value;
					this.SendPropertyChanged("FavMovies");
					this.OnFavMoviesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICQNumber", DbType="VarChar(50)")]
		public string ICQNumber
		{
			get
			{
				return this._ICQNumber;
			}
			set
			{
				if ((this._ICQNumber != value))
				{
					this.OnICQNumberChanging(value);
					this.SendPropertyChanging();
					this._ICQNumber = value;
					this.SendPropertyChanged("ICQNumber");
					this.OnICQNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCRelationTypeCode", DbType="Int")]
		public System.Nullable<int> HCRelationTypeCode
		{
			get
			{
				return this._HCRelationTypeCode;
			}
			set
			{
				if ((this._HCRelationTypeCode != value))
				{
					this.OnHCRelationTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCRelationTypeCode = value;
					this.SendPropertyChanged("HCRelationTypeCode");
					this.OnHCRelationTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoForFun", DbType="NVarChar(1000)")]
		public string DoForFun
		{
			get
			{
				return this._DoForFun;
			}
			set
			{
				if ((this._DoForFun != value))
				{
					this.OnDoForFunChanging(value);
					this.SendPropertyChanging();
					this._DoForFun = value;
					this.SendPropertyChanged("DoForFun");
					this.OnDoForFunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IInviteMeToJoinGroup", DbType="Bit")]
		public System.Nullable<bool> IInviteMeToJoinGroup
		{
			get
			{
				return this._IInviteMeToJoinGroup;
			}
			set
			{
				if ((this._IInviteMeToJoinGroup != value))
				{
					this.OnIInviteMeToJoinGroupChanging(value);
					this.SendPropertyChanging();
					this._IInviteMeToJoinGroup = value;
					this.SendPropertyChanged("IInviteMeToJoinGroup");
					this.OnIInviteMeToJoinGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISendMessage", DbType="Bit")]
		public System.Nullable<bool> ISendMessage
		{
			get
			{
				return this._ISendMessage;
			}
			set
			{
				if ((this._ISendMessage != value))
				{
					this.OnISendMessageChanging(value);
					this.SendPropertyChanging();
					this._ISendMessage = value;
					this.SendPropertyChanged("ISendMessage");
					this.OnISendMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IAddMeAsFriend", DbType="Bit")]
		public System.Nullable<bool> IAddMeAsFriend
		{
			get
			{
				return this._IAddMeAsFriend;
			}
			set
			{
				if ((this._IAddMeAsFriend != value))
				{
					this.OnIAddMeAsFriendChanging(value);
					this.SendPropertyChanging();
					this._IAddMeAsFriend = value;
					this.SendPropertyChanged("IAddMeAsFriend");
					this.OnIAddMeAsFriendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IConnectMeAsFan", DbType="Bit")]
		public System.Nullable<bool> IConnectMeAsFan
		{
			get
			{
				return this._IConnectMeAsFan;
			}
			set
			{
				if ((this._IConnectMeAsFan != value))
				{
					this.OnIConnectMeAsFanChanging(value);
					this.SendPropertyChanging();
					this._IConnectMeAsFan = value;
					this.SendPropertyChanged("IConnectMeAsFan");
					this.OnIConnectMeAsFanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IConfirmFriendshipReq", DbType="Bit")]
		public System.Nullable<bool> IConfirmFriendshipReq
		{
			get
			{
				return this._IConfirmFriendshipReq;
			}
			set
			{
				if ((this._IConfirmFriendshipReq != value))
				{
					this.OnIConfirmFriendshipReqChanging(value);
					this.SendPropertyChanging();
					this._IConfirmFriendshipReq = value;
					this.SendPropertyChanged("IConfirmFriendshipReq");
					this.OnIConfirmFriendshipReqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPostMeGlobalMessage", DbType="Bit")]
		public System.Nullable<bool> IPostMeGlobalMessage
		{
			get
			{
				return this._IPostMeGlobalMessage;
			}
			set
			{
				if ((this._IPostMeGlobalMessage != value))
				{
					this.OnIPostMeGlobalMessageChanging(value);
					this.SendPropertyChanging();
					this._IPostMeGlobalMessage = value;
					this.SendPropertyChanged("IPostMeGlobalMessage");
					this.OnIPostMeGlobalMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPostMePrivateMessage", DbType="Bit")]
		public System.Nullable<bool> IPostMePrivateMessage
		{
			get
			{
				return this._IPostMePrivateMessage;
			}
			set
			{
				if ((this._IPostMePrivateMessage != value))
				{
					this.OnIPostMePrivateMessageChanging(value);
					this.SendPropertyChanging();
					this._IPostMePrivateMessage = value;
					this.SendPropertyChanged("IPostMePrivateMessage");
					this.OnIPostMePrivateMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISuggestsFriends", DbType="Bit")]
		public System.Nullable<bool> ISuggestsFriends
		{
			get
			{
				return this._ISuggestsFriends;
			}
			set
			{
				if ((this._ISuggestsFriends != value))
				{
					this.OnISuggestsFriendsChanging(value);
					this.SendPropertyChanging();
					this._ISuggestsFriends = value;
					this.SendPropertyChanged("ISuggestsFriends");
					this.OnISuggestsFriendsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IAcceptFriendISuggested", DbType="Bit")]
		public System.Nullable<bool> IAcceptFriendISuggested
		{
			get
			{
				return this._IAcceptFriendISuggested;
			}
			set
			{
				if ((this._IAcceptFriendISuggested != value))
				{
					this.OnIAcceptFriendISuggestedChanging(value);
					this.SendPropertyChanging();
					this._IAcceptFriendISuggested = value;
					this.SendPropertyChanged("IAcceptFriendISuggested");
					this.OnIAcceptFriendISuggestedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITagsMeOnPhoto", DbType="Bit")]
		public System.Nullable<bool> ITagsMeOnPhoto
		{
			get
			{
				return this._ITagsMeOnPhoto;
			}
			set
			{
				if ((this._ITagsMeOnPhoto != value))
				{
					this.OnITagsMeOnPhotoChanging(value);
					this.SendPropertyChanging();
					this._ITagsMeOnPhoto = value;
					this.SendPropertyChanged("ITagsMeOnPhoto");
					this.OnITagsMeOnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICommentOnMyPhoto", DbType="Bit")]
		public System.Nullable<bool> ICommentOnMyPhoto
		{
			get
			{
				return this._ICommentOnMyPhoto;
			}
			set
			{
				if ((this._ICommentOnMyPhoto != value))
				{
					this.OnICommentOnMyPhotoChanging(value);
					this.SendPropertyChanging();
					this._ICommentOnMyPhoto = value;
					this.SendPropertyChanged("ICommentOnMyPhoto");
					this.OnICommentOnMyPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IRequestToJoinMyGroup", DbType="Bit")]
		public System.Nullable<bool> IRequestToJoinMyGroup
		{
			get
			{
				return this._IRequestToJoinMyGroup;
			}
			set
			{
				if ((this._IRequestToJoinMyGroup != value))
				{
					this.OnIRequestToJoinMyGroupChanging(value);
					this.SendPropertyChanging();
					this._IRequestToJoinMyGroup = value;
					this.SendPropertyChanged("IRequestToJoinMyGroup");
					this.OnIRequestToJoinMyGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IInviteMeAnEvent", DbType="Bit")]
		public System.Nullable<bool> IInviteMeAnEvent
		{
			get
			{
				return this._IInviteMeAnEvent;
			}
			set
			{
				if ((this._IInviteMeAnEvent != value))
				{
					this.OnIInviteMeAnEventChanging(value);
					this.SendPropertyChanging();
					this._IInviteMeAnEvent = value;
					this.SendPropertyChanged("IInviteMeAnEvent");
					this.OnIInviteMeAnEventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IChangeMyEventDate", DbType="Bit")]
		public System.Nullable<bool> IChangeMyEventDate
		{
			get
			{
				return this._IChangeMyEventDate;
			}
			set
			{
				if ((this._IChangeMyEventDate != value))
				{
					this.OnIChangeMyEventDateChanging(value);
					this.SendPropertyChanging();
					this._IChangeMyEventDate = value;
					this.SendPropertyChanged("IChangeMyEventDate");
					this.OnIChangeMyEventDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICommentOnMyNote", DbType="Bit")]
		public System.Nullable<bool> ICommentOnMyNote
		{
			get
			{
				return this._ICommentOnMyNote;
			}
			set
			{
				if ((this._ICommentOnMyNote != value))
				{
					this.OnICommentOnMyNoteChanging(value);
					this.SendPropertyChanging();
					this._ICommentOnMyNote = value;
					this.SendPropertyChanged("ICommentOnMyNote");
					this.OnICommentOnMyNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICommentMyLink", DbType="Bit")]
		public System.Nullable<bool> ICommentMyLink
		{
			get
			{
				return this._ICommentMyLink;
			}
			set
			{
				if ((this._ICommentMyLink != value))
				{
					this.OnICommentMyLinkChanging(value);
					this.SendPropertyChanging();
					this._ICommentMyLink = value;
					this.SendPropertyChanged("ICommentMyLink");
					this.OnICommentMyLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICommentAfterMeInLink", DbType="Bit")]
		public System.Nullable<bool> ICommentAfterMeInLink
		{
			get
			{
				return this._ICommentAfterMeInLink;
			}
			set
			{
				if ((this._ICommentAfterMeInLink != value))
				{
					this.OnICommentAfterMeInLinkChanging(value);
					this.SendPropertyChanging();
					this._ICommentAfterMeInLink = value;
					this.SendPropertyChanged("ICommentAfterMeInLink");
					this.OnICommentAfterMeInLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICommentAfterMeOnGeneralMessage", DbType="Bit")]
		public System.Nullable<bool> ICommentAfterMeOnGeneralMessage
		{
			get
			{
				return this._ICommentAfterMeOnGeneralMessage;
			}
			set
			{
				if ((this._ICommentAfterMeOnGeneralMessage != value))
				{
					this.OnICommentAfterMeOnGeneralMessageChanging(value);
					this.SendPropertyChanging();
					this._ICommentAfterMeOnGeneralMessage = value;
					this.SendPropertyChanged("ICommentAfterMeOnGeneralMessage");
					this.OnICommentAfterMeOnGeneralMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemindUpload", DbType="Bit")]
		public System.Nullable<bool> RemindUpload
		{
			get
			{
				return this._RemindUpload;
			}
			set
			{
				if ((this._RemindUpload != value))
				{
					this.OnRemindUploadChanging(value);
					this.SendPropertyChanging();
					this._RemindUpload = value;
					this.SendPropertyChanged("RemindUpload");
					this.OnRemindUploadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AIMNumber", DbType="VarChar(50)")]
		public string AIMNumber
		{
			get
			{
				return this._AIMNumber;
			}
			set
			{
				if ((this._AIMNumber != value))
				{
					this.OnAIMNumberChanging(value);
					this.SendPropertyChanging();
					this._AIMNumber = value;
					this.SendPropertyChanged("AIMNumber");
					this.OnAIMNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkypeName", DbType="VarChar(50)")]
		public string SkypeName
		{
			get
			{
				return this._SkypeName;
			}
			set
			{
				if ((this._SkypeName != value))
				{
					this.OnSkypeNameChanging(value);
					this.SendPropertyChanging();
					this._SkypeName = value;
					this.SendPropertyChanged("SkypeName");
					this.OnSkypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JabberNumber", DbType="VarChar(50)")]
		public string JabberNumber
		{
			get
			{
				return this._JabberNumber;
			}
			set
			{
				if ((this._JabberNumber != value))
				{
					this.OnJabberNumberChanging(value);
					this.SendPropertyChanging();
					this._JabberNumber = value;
					this.SendPropertyChanged("JabberNumber");
					this.OnJabberNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="VarChar(50)")]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this.OnMobileNumberChanging(value);
					this.SendPropertyChanging();
					this._MobileNumber = value;
					this.SendPropertyChanged("MobileNumber");
					this.OnMobileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSeekGenderCode", DbType="Int")]
		public System.Nullable<int> HCSeekGenderCode
		{
			get
			{
				return this._HCSeekGenderCode;
			}
			set
			{
				if ((this._HCSeekGenderCode != value))
				{
					this.OnHCSeekGenderCodeChanging(value);
					this.SendPropertyChanging();
					this._HCSeekGenderCode = value;
					this.SendPropertyChanged("HCSeekGenderCode");
					this.OnHCSeekGenderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCCamStatusCode", DbType="Int")]
		public System.Nullable<int> HCCamStatusCode
		{
			get
			{
				return this._HCCamStatusCode;
			}
			set
			{
				if ((this._HCCamStatusCode != value))
				{
					this.OnHCCamStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCCamStatusCode = value;
					this.SendPropertyChanged("HCCamStatusCode");
					this.OnHCCamStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCUserTypeCode", DbType="Int")]
		public System.Nullable<int> HCUserTypeCode
		{
			get
			{
				return this._HCUserTypeCode;
			}
			set
			{
				if ((this._HCUserTypeCode != value))
				{
					this.OnHCUserTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCUserTypeCode = value;
					this.SendPropertyChanged("HCUserTypeCode");
					this.OnHCUserTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCTallCode", DbType="Int")]
		public System.Nullable<int> HCTallCode
		{
			get
			{
				return this._HCTallCode;
			}
			set
			{
				if ((this._HCTallCode != value))
				{
					this.OnHCTallCodeChanging(value);
					this.SendPropertyChanging();
					this._HCTallCode = value;
					this.SendPropertyChanged("HCTallCode");
					this.OnHCTallCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCWeightCode", DbType="Int")]
		public System.Nullable<int> HCWeightCode
		{
			get
			{
				return this._HCWeightCode;
			}
			set
			{
				if ((this._HCWeightCode != value))
				{
					this.OnHCWeightCodeChanging(value);
					this.SendPropertyChanging();
					this._HCWeightCode = value;
					this.SendPropertyChanged("HCWeightCode");
					this.OnHCWeightCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCHairColorCode", DbType="Int")]
		public System.Nullable<int> HCHairColorCode
		{
			get
			{
				return this._HCHairColorCode;
			}
			set
			{
				if ((this._HCHairColorCode != value))
				{
					this.OnHCHairColorCodeChanging(value);
					this.SendPropertyChanging();
					this._HCHairColorCode = value;
					this.SendPropertyChanged("HCHairColorCode");
					this.OnHCHairColorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEyeColorCode", DbType="Int")]
		public System.Nullable<int> HCEyeColorCode
		{
			get
			{
				return this._HCEyeColorCode;
			}
			set
			{
				if ((this._HCEyeColorCode != value))
				{
					this.OnHCEyeColorCodeChanging(value);
					this.SendPropertyChanging();
					this._HCEyeColorCode = value;
					this.SendPropertyChanged("HCEyeColorCode");
					this.OnHCEyeColorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCBodyTypeCode", DbType="Int")]
		public System.Nullable<int> HCBodyTypeCode
		{
			get
			{
				return this._HCBodyTypeCode;
			}
			set
			{
				if ((this._HCBodyTypeCode != value))
				{
					this.OnHCBodyTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCBodyTypeCode = value;
					this.SendPropertyChanged("HCBodyTypeCode");
					this.OnHCBodyTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCRaceCode", DbType="Int")]
		public System.Nullable<int> HCRaceCode
		{
			get
			{
				return this._HCRaceCode;
			}
			set
			{
				if ((this._HCRaceCode != value))
				{
					this.OnHCRaceCodeChanging(value);
					this.SendPropertyChanging();
					this._HCRaceCode = value;
					this.SendPropertyChanged("HCRaceCode");
					this.OnHCRaceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCMarritalStatusCode", DbType="Int")]
		public System.Nullable<int> HCMarritalStatusCode
		{
			get
			{
				return this._HCMarritalStatusCode;
			}
			set
			{
				if ((this._HCMarritalStatusCode != value))
				{
					this.OnHCMarritalStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCMarritalStatusCode = value;
					this.SendPropertyChanged("HCMarritalStatusCode");
					this.OnHCMarritalStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCKidNoCode", DbType="Int")]
		public System.Nullable<int> HCKidNoCode
		{
			get
			{
				return this._HCKidNoCode;
			}
			set
			{
				if ((this._HCKidNoCode != value))
				{
					this.OnHCKidNoCodeChanging(value);
					this.SendPropertyChanging();
					this._HCKidNoCode = value;
					this.SendPropertyChanged("HCKidNoCode");
					this.OnHCKidNoCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCWantKidCode", DbType="Int")]
		public System.Nullable<int> HCWantKidCode
		{
			get
			{
				return this._HCWantKidCode;
			}
			set
			{
				if ((this._HCWantKidCode != value))
				{
					this.OnHCWantKidCodeChanging(value);
					this.SendPropertyChanging();
					this._HCWantKidCode = value;
					this.SendPropertyChanged("HCWantKidCode");
					this.OnHCWantKidCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCProfessionCode", DbType="Int")]
		public System.Nullable<int> HCProfessionCode
		{
			get
			{
				return this._HCProfessionCode;
			}
			set
			{
				if ((this._HCProfessionCode != value))
				{
					this.OnHCProfessionCodeChanging(value);
					this.SendPropertyChanging();
					this._HCProfessionCode = value;
					this.SendPropertyChanged("HCProfessionCode");
					this.OnHCProfessionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCIncomeCode", DbType="Int")]
		public System.Nullable<int> HCIncomeCode
		{
			get
			{
				return this._HCIncomeCode;
			}
			set
			{
				if ((this._HCIncomeCode != value))
				{
					this.OnHCIncomeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCIncomeCode = value;
					this.SendPropertyChanged("HCIncomeCode");
					this.OnHCIncomeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCLang1Code", DbType="Int")]
		public System.Nullable<int> HCLang1Code
		{
			get
			{
				return this._HCLang1Code;
			}
			set
			{
				if ((this._HCLang1Code != value))
				{
					this.OnHCLang1CodeChanging(value);
					this.SendPropertyChanging();
					this._HCLang1Code = value;
					this.SendPropertyChanged("HCLang1Code");
					this.OnHCLang1CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCLang2Code", DbType="Int")]
		public System.Nullable<int> HCLang2Code
		{
			get
			{
				return this._HCLang2Code;
			}
			set
			{
				if ((this._HCLang2Code != value))
				{
					this.OnHCLang2CodeChanging(value);
					this.SendPropertyChanging();
					this._HCLang2Code = value;
					this.SendPropertyChanged("HCLang2Code");
					this.OnHCLang2CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCLang3Code", DbType="Int")]
		public System.Nullable<int> HCLang3Code
		{
			get
			{
				return this._HCLang3Code;
			}
			set
			{
				if ((this._HCLang3Code != value))
				{
					this.OnHCLang3CodeChanging(value);
					this.SendPropertyChanging();
					this._HCLang3Code = value;
					this.SendPropertyChanged("HCLang3Code");
					this.OnHCLang3CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCLang4Code", DbType="Int")]
		public System.Nullable<int> HCLang4Code
		{
			get
			{
				return this._HCLang4Code;
			}
			set
			{
				if ((this._HCLang4Code != value))
				{
					this.OnHCLang4CodeChanging(value);
					this.SendPropertyChanging();
					this._HCLang4Code = value;
					this.SendPropertyChanged("HCLang4Code");
					this.OnHCLang4CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEducationCode", DbType="Int")]
		public System.Nullable<int> HCEducationCode
		{
			get
			{
				return this._HCEducationCode;
			}
			set
			{
				if ((this._HCEducationCode != value))
				{
					this.OnHCEducationCodeChanging(value);
					this.SendPropertyChanging();
					this._HCEducationCode = value;
					this.SendPropertyChanged("HCEducationCode");
					this.OnHCEducationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPoliticalViewCode", DbType="Int")]
		public System.Nullable<int> HCPoliticalViewCode
		{
			get
			{
				return this._HCPoliticalViewCode;
			}
			set
			{
				if ((this._HCPoliticalViewCode != value))
				{
					this.OnHCPoliticalViewCodeChanging(value);
					this.SendPropertyChanging();
					this._HCPoliticalViewCode = value;
					this.SendPropertyChanged("HCPoliticalViewCode");
					this.OnHCPoliticalViewCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCReligionCode", DbType="Int")]
		public System.Nullable<int> HCReligionCode
		{
			get
			{
				return this._HCReligionCode;
			}
			set
			{
				if ((this._HCReligionCode != value))
				{
					this.OnHCReligionCodeChanging(value);
					this.SendPropertyChanging();
					this._HCReligionCode = value;
					this.SendPropertyChanged("HCReligionCode");
					this.OnHCReligionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSmokeCode", DbType="Int")]
		public System.Nullable<int> HCSmokeCode
		{
			get
			{
				return this._HCSmokeCode;
			}
			set
			{
				if ((this._HCSmokeCode != value))
				{
					this.OnHCSmokeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCSmokeCode = value;
					this.SendPropertyChanged("HCSmokeCode");
					this.OnHCSmokeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCAlcoholCode", DbType="Int")]
		public System.Nullable<int> HCAlcoholCode
		{
			get
			{
				return this._HCAlcoholCode;
			}
			set
			{
				if ((this._HCAlcoholCode != value))
				{
					this.OnHCAlcoholCodeChanging(value);
					this.SendPropertyChanging();
					this._HCAlcoholCode = value;
					this.SendPropertyChanged("HCAlcoholCode");
					this.OnHCAlcoholCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCHumorCode", DbType="Int")]
		public System.Nullable<int> HCHumorCode
		{
			get
			{
				return this._HCHumorCode;
			}
			set
			{
				if ((this._HCHumorCode != value))
				{
					this.OnHCHumorCodeChanging(value);
					this.SendPropertyChanging();
					this._HCHumorCode = value;
					this.SendPropertyChanged("HCHumorCode");
					this.OnHCHumorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Favorites", DbType="NVarChar(1000)")]
		public string Favorites
		{
			get
			{
				return this._Favorites;
			}
			set
			{
				if ((this._Favorites != value))
				{
					this.OnFavoritesChanging(value);
					this.SendPropertyChanging();
					this._Favorites = value;
					this.SendPropertyChanged("Favorites");
					this.OnFavoritesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HobbyComment", DbType="NVarChar(1000)")]
		public string HobbyComment
		{
			get
			{
				return this._HobbyComment;
			}
			set
			{
				if ((this._HobbyComment != value))
				{
					this.OnHobbyCommentChanging(value);
					this.SendPropertyChanging();
					this._HobbyComment = value;
					this.SendPropertyChanged("HobbyComment");
					this.OnHobbyCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EduComment", DbType="NVarChar(1000)")]
		public string EduComment
		{
			get
			{
				return this._EduComment;
			}
			set
			{
				if ((this._EduComment != value))
				{
					this.OnEduCommentChanging(value);
					this.SendPropertyChanging();
					this._EduComment = value;
					this.SendPropertyChanged("EduComment");
					this.OnEduCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaceInfo", DbType="NVarChar(1000)")]
		public string RaceInfo
		{
			get
			{
				return this._RaceInfo;
			}
			set
			{
				if ((this._RaceInfo != value))
				{
					this.OnRaceInfoChanging(value);
					this.SendPropertyChanging();
					this._RaceInfo = value;
					this.SendPropertyChanged("RaceInfo");
					this.OnRaceInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPassword", DbType="NVarChar(50)")]
		public string EmailPassword
		{
			get
			{
				return this._EmailPassword;
			}
			set
			{
				if ((this._EmailPassword != value))
				{
					this.OnEmailPasswordChanging(value);
					this.SendPropertyChanging();
					this._EmailPassword = value;
					this.SendPropertyChanged("EmailPassword");
					this.OnEmailPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DockState", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DockState
		{
			get
			{
				return this._DockState;
			}
			set
			{
				if ((this._DockState != value))
				{
					this.OnDockStateChanging(value);
					this.SendPropertyChanging();
					this._DockState = value;
					this.SendPropertyChanged("DockState");
					this.OnDockStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPicStatusCode", DbType="Int")]
		public System.Nullable<int> HCPicStatusCode
		{
			get
			{
				return this._HCPicStatusCode;
			}
			set
			{
				if ((this._HCPicStatusCode != value))
				{
					this.OnHCPicStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCPicStatusCode = value;
					this.SendPropertyChanged("HCPicStatusCode");
					this.OnHCPicStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginTime
		{
			get
			{
				return this._LastLoginTime;
			}
			set
			{
				if ((this._LastLoginTime != value))
				{
					this.OnLastLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LastLoginTime = value;
					this.SendPropertyChanged("LastLoginTime");
					this.OnLastLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegDate
		{
			get
			{
				return this._RegDate;
			}
			set
			{
				if ((this._RegDate != value))
				{
					this.OnRegDateChanging(value);
					this.SendPropertyChanging();
					this._RegDate = value;
					this.SendPropertyChanged("RegDate");
					this.OnRegDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdsEmailSent", DbType="Bit")]
		public System.Nullable<bool> AdsEmailSent
		{
			get
			{
				return this._AdsEmailSent;
			}
			set
			{
				if ((this._AdsEmailSent != value))
				{
					this.OnAdsEmailSentChanging(value);
					this.SendPropertyChanging();
					this._AdsEmailSent = value;
					this.SendPropertyChanged("AdsEmailSent");
					this.OnAdsEmailSentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
